name: Publish

on:
  workflow_dispatch:
    inputs:
      version_bump:
        description: 'Select version bump'
        required: true
        type: choice
        options:
          - major
          - minor
          - patch
        default: 'minor'

jobs:
  publish:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Bump version
        id: bump_version
        uses: MeilCli/bump-release-action@v2
        with:
          config_path: '.github/bump.yml'
          bump: ${{ github.event.inputs.version_bump }}

      - name: Publish to Maven Central
        env:
          NEXT_VERSION: ${{ steps.bump_version.outputs.next_version }}
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_IN_MEMORY_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_IN_MEMORY_KEY_PASSWORD }}
        run: ./gradlew publish
